[shell]
program               = "/usr/bin/zsh"
args                  = [ "--login", ]

[env]
TERM                  = "xterm-256color"

[window]
dimensions            = { columns = 0, lines = 0 }
position              = { x = 0, y = 0 }
padding               = { x = 0, y = 0 }
dynamic_padding       = true
decorations           = "None"
opacity               = 1.0
blur                  = true

[scrolling]
history               = 65535
#multiplier            = 3
[font]
normal                = { family = "Iosevka NF", style = "Regular" }
bold                  = { family = "Iosevka NF", style = "Bold" }
italic                = { family = "Iosevka NF", style = "Italic" }
bold_italic           = { family = "Iosevka NF", style = "Bold Italic" }
size                  = 10 
offset                = { x = 0, y = 0 }
glyph_offset          = { x = 0, y = 0 }



# [bell]
# animation             = "EaseOutExpo"
# duration              = 0
# color                 = "#C0C5CE"
# command               = { program = "notify-send", args = ["alacritty", "bell",] }


[selection]
#semantic_escape_chars = ",│‘|="' ()[]{}<>t"
save_to_clipboard     = true

[cursor.style]
shape                 = "Block"
blinking              = "Always"
#
[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "always"
#

[cursor]
blink_interval        = 500
blink_timeout         = 0
unfocused_hollow      = true
thickness             = 0.20

[terminal]
#osc52                 = "OnlyCopy"

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
]
[general]
import = [
    # "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
    "~/Documents/dotfiles/config/alacritty/themes/themes/ayu_dark.toml"
]


