set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set signcolumn="yes"
set mouse=a
set showtabline=1
set termguicolors
set timeoutlen=400
set updatetime=250
set laststatus=2
set statusline=%t\ \ \\|
set hlsearch
set expandtab
set shiftwidth=2
set smartindent
set tabstop=2
set softtabstop=2
set ignorecase
set smartcase
set updatetime=250
set wildmenu
set splitbelow
set splitright
set cursorline
set number
set relativenumber
set ruler
set nocompatible
set background=dark
syntax enable
filetype plugin indent on
packadd! editorconfig
nnoremap <C-h> <C-w>h 
nnoremap <C-j> <C-w>j 
nnoremap <C-k> <C-w>k 
nnoremap <C-l> <C-w>l 
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
"inoremap jj <ESC>
"inoremap jj <ESC>:noh<CR>
inoremap <C-[> <ESC>:noh<CR>
vnoremap > >gv
vnoremap < <gv
vnoremap <silent> J :m '>+1<cr>gv=gv
vnoremap <silent> K :m '<-2<cr>gv=gv
let g:netrw_bufsettings="noma nomod nonu nobl nowrap ro rnu"
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"
colorscheme murphy
