-- display args
-- vim.api.nvim_create_autocmd("LspAttach", {
--     callback = function(args)
--         local client = assert(vim.lsp.get_client_by_id(args.data.client_id))
--         if client.server_capabilities.inlayHintProvider then
--             vim.lsp.inlay_hint.enable(true)
--             -- autocompletition
--              vim.lsp.completion.enable(true)
--         end
--     end,
-- })
