-- local M = {}
-- M.config = function()
-- 	require("jdtls").start_or_attach({
-- 		cmd = {
-- 			"-configuration",
-- 			"/home/jppm/.local/share/nvim/mason/bin/jdtls",
-- 			"-javaagent" .. "/home/jppm/.local/share/nvim/mason/share/jdtls/lombok.jar",
-- 		},
-- 		root_dir = vim.fs.dirname(vim.fs.find({ "gradlew", ".git", "mvnw" }, { upward = true })[1]),
-- 		settings = {
-- 			java = {
-- 				eclipse = {
-- 					downloadSources = true,
-- 				},
-- 				configuration = {
-- 					updateBuildConfiguration = "interactive",
-- 				},
-- 				maven = {
-- 					downloadSources = true,
-- 				},
-- 				implementationsCodeLens = {
-- 					enabled = true,
-- 				},
-- 				referencesCodeLens = {
-- 					enabled = true,
-- 				},
-- 				references = {
-- 					includeDecompiledSources = true,
-- 				},
-- 				format = {
-- 					enabled = true,
-- 					settings = {
-- 						url = vim.fn.stdpath("config") .. "/lang-servers/intellij-java-google-style.xml",
-- 						profile = "GoogleStyle",
-- 					},
-- 				},
-- 			},
-- 			signatureHelp = { enabled = true },
-- 			completion = {
-- 				favoriteStaticMembers = {
-- 					"org.hamcrest.MatcherAssert.assertThat",
-- 					"org.hamcrest.Matchers.*",
-- 					"org.hamcrest.CoreMatchers.*",
-- 					"org.junit.jupiter.api.Assertions.*",
-- 					"java.util.Objects.requireNonNull",
-- 					"java.util.Objects.requireNonNullElse",
-- 					"org.mockito.Mockito.*",
-- 				},
-- 			},
-- 			contentProvider = { preferred = "fernflower" },
-- 			extendedClientCapabilities = extendedClientCapabilities,
-- 			sources = {
-- 				organizeImports = {
-- 					starThreshold = 9999,
-- 					staticStarThreshold = 9999,
-- 				},
-- 			},
-- 			codeGeneration = {
-- 				toString = {
-- 					template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}",
-- 				},
-- 				useBlocks = true,
-- 			},
-- 		},
--
-- 		flags = {
-- 			allow_incremental_sync = true,
-- 		},
-- 		-- Language server `initializationOptions`
-- 		-- You need to extend the `bundles` with paths to jar files
-- 		-- if you want to use additional eclipse.jdt.ls plugins.
-- 		--
-- 		-- See https://github.com/mfussenegger/nvim-jdtls#java-debug-installation
-- 		--
-- 		-- If you don't plan on using the debugger or other eclipse.jdt.ls plugins you can remove this
-- 		init_options = {
-- 			bundles = {},
-- 		},
-- 	})
-- end
--
-- return M
